server:
  port: 8083
  use-forward-headers: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/order
    username: test
    password: passwd
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9103/uaa/token_keys
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
mq:
  submit-order-saga:
    hostname: localhost
    port: 5672
    exchange: amq.direct
    routing-key: submit-order-saga
    queue:
      name: submit-order-saga
feign:
  oauth:
    authorization-grant-type: password
    access-token-uri: http://localhost:9103/uaa/oauth/token
    client:
      id: service
      secret: secret
      scope: uaa.user,openid,profile,email,catalog.read,inventory.read,inventory.write
      username: order_service
      password: password
      
    