server:
  port: 8083
  use-forward-headers: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/order
    username: test
    password: passwd
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
mq:
  submit-order-saga:
    hostname: localhost
    port: 5672
    exchange: amq.direct
    routing-key: submit-order-saga
    queue:
      name: submit-order-saga